services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      DEBUG: "true"
      DATABASE_URL: postgresql+asyncpg://sentinelcore:sentinelcore@postgres:5432/sentinelcore
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://sentinelcore:sentinelcore@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sentinelcore
      POSTGRES_PASSWORD: sentinelcore
      POSTGRES_DB: sentinelcore
    ports:
      - "5433:5432"
    volumes:
      - sentinelcore_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinelcore"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: sentinelcore
      RABBITMQ_DEFAULT_PASS: sentinelcore
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sentinelcore_postgres_data:
